#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd

In [2]:
data_path = '../data/supermarket_sales.csv'
df = pd.read_csv(data_path)

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [ ]:
df.groupby("Branch")[['Total', 'gross income']].sum().sort_values(by=['gross income', 'Total'], ascending=False).reset_index()
# Філіал C має найвищий Total і Gross

  Branch        Total  gross income
0      C  110568.7065     5265.1765
1      A  106200.3705     5057.1605
2      B  106197.6720     5057.0320

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [ ]:
df.groupby(["Branch", "City"])[['Total', 'gross income']].sum().sort_values(by=['gross income', 'Total'], ascending=False).head(1).reset_index()
# Філіал з найвищим прибутком знаходиться в місті Naypyitaw. Тут можна розмістити ще один магазин.

  Branch       City        Total  gross income
0      C  Naypyitaw  110568.7065     5265.1765

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [24]:
invoices_by_category = pd.pivot_table(df, index='Branch', columns='Product line', values='Invoice ID', aggfunc='count')
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [37]:
invoices_by_category['Electronic accessories'].idxmax()

'A'

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

1-ше питання. Більше покупок роблять і на більшу суму купують жінки чи чоловіки?
Виконавши код, бачимо, що жінки роблять трохи більше покупок і на трохи більшу суму.
Відповідь на це питання може бути використана для прийняття бізнес рішень таким чином: робити рекламу з участю жінок і рекламувати товари, що потенційно цікаві жінкам.

In [42]:
df.groupby("Gender").agg({'Invoice ID': 'count', 'Total': 'sum'})

        Invoice ID       Total
Gender
Female         501  167882.925
Male           499  155083.824

2-ге питання. Які категорії товарів приносять більший прибуток від жінок, а які від чоловіків?
Згідно з даними, жінки більше витрачають грошей на Fashion accessories, Food and beverages, Home and lifestyle, Sports and travel. А чоловіки - на Electronic accessories, Health and beauty.
Відповідь на це питання може бути використана для прийняття бізнес рішень таким чином: робити рекламу для чоловіків з фокусом на те, що вони можуть порадувати своїх жінок прикрасами, купувати здорову їжу, щоб довше залишатися молодими, купувати спортивний одяг, щоб було більше мотивації на спорт, більше подорожувати і для цього купувати необхідні речі. А в рекламі для жінок можна заохочувати їх купувати Electronic accessories, щоб полегшити собі життя (робот пилосос, посудомийка і т.д.), а також засоби для здоров'я і краси, можливо, зробити на них знижку.

In [44]:
invoices_by_gender = pd.pivot_table(df, index='Gender', columns='Product line', values='Total', aggfunc='sum')
invoices_by_gender

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Gender,,,,,,
Female,27102.0225,30437.400,33170.9175,18560.9865,30036.8775,28574.7210
Male,27235.5090,23868.495,22973.9265,30632.7525,23825.0355,26548.1055

3-тє питання. У якому місті більше купують жінки, а в якому чоловіки?
Відповідно до виведених даних, жінки більше роблять покупки у містах Naypyitaw і Yangon, а чоловіки в Mandalay. У Mandalay треба зробити більше реклами і акцій, спрямованих на товари для жінок, а в інших - для чоловіків.

In [46]:
city_gender = pd.pivot_table(df, index='Gender', columns=['City', 'Branch'], values='Total', aggfunc='sum')
city_gender

City     Mandalay   Naypyitaw      Yangon
Branch          B           C           A
Gender
Female  52928.295  61685.4630  53269.1670
Male    53269.377  48883.2435  52931.2035